[package]
name = "wasmer-tests/wasmer-edge-mkdocs-sample"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-mkdocs-sample website"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "site"
