[package]
name = "wasmer-tests/wasmer-edge-docusaurus-sample"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-docusaurus-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
