name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}
  ASTRO_DIR: ./wasmer-edge-astro
  DOCUSAURUS_DIR: ./wasmer-edge-docusaurus
  GATSBY_DIR: ./wasmer-edge-gatsby
  HUGO_DIR: ./wasmer-edge-hugo
  MKDOCS_DIR: ./wasmer-edge-mkdocs
  NEXTJS_DIR: ./wasmer-edge-next-ssg
  NUXT_DIR: ./wasmer-edge-nuxt
  SVELTE_DIR: ./wasmer-edge-svelte

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_astro:
    name: Build and deploy an Astro website to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Astro's dependencies
        working-directory: ${{env.ASTRO_DIR}}
        run: pnpm install
      - name: Build Astro
        working-directory: ${{env.ASTRO_DIR}}
        run: pnpm build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.ASTRO_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.ASTRO_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_docusaurus:
    name: Build and Deploy Docusaurus based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Docusaurus's dependencies
        working-directory: ${{env.DOCUSAURUS_DIR}}
        run: pnpm install
      - name: Build Docusaurus
        working-directory: ${{env.DOCUSAURUS_DIR}}
        run: pnpm build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.DOCUSAURUS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.DOCUSAURUS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_gatsby:
    name: Build and Deploy Gatsby based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.7.0"
      - name: Install Gatsby's dependencies
        working-directory: ${{env.GATSBY_DIR}}
        run: npm install
      - name: Build Gatsby
        working-directory: ${{env.GATSBY_DIR}}
        run: npm run build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.GATSBY_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.GATSBY_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_hugo:
    name: Build and Deploy Hugo based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.119.0"
      - name: Build Hugo
        working-directory: ${{env.HUGO_DIR}}
        run: hugo --minify
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.HUGO_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.HUGO_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_mkdocs:
    name: Build and Deploy MKDocs based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Build MKdocs
        working-directory: ${{env.MKDOCS_DIR}}
        run: mkdocs build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.MKDOCS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.MKDOCS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_next_ssg:
    name: Build and Deploy Next based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Next's dependencies
        working-directory: ${{env.NEXTJS_DIR}}
        run: pnpm install
      - name: Build Next.js SSG
        working-directory: ${{env.NEXTJS_DIR}}
        run: pnpm build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.NEXTJS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.NEXTJS_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_nuxt:
    name: Build and Deploy Nuxt based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Nuxt's dependencies
        working-directory: ${{env.NUXT_DIR}}
        run: pnpm install
      - name: Build Nuxt
        working-directory: ${{env.NUXT_DIR}}
        run: pnpm build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.NUXT_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.NUXT_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
  build_and_deploy_svelte:
    name: Build and Deploy Svelte based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Svelte's dependencies
        working-directory: ${{env.SVELTE_DIR}}
        run: pnpm install
      - name: Build Svelte
        working-directory: ${{env.SVELTE_DIR}}
        run: pnpm build
      - name: Deploy app to wasmer.wtf
        working-directory: ${{env.SVELTE_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WAPM_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
        continue-on-error: true
      - name: Deploy app to wasmer.io
        working-directory: ${{env.SVELTE_DIR}}
        run: wasmer deploy --registry="https://registry.wasmer.io/graphql" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
